# This is the network config written by 'subiquity'
network:
  ethernets:
    ens3:
      dhcp4: false
      addresses: [<real_address>/24]
      optional: true
      routes:
        - to: default
          via: 192.168.122.1
      nameservers:
        addresses: [192.168.122.1, 114.114.114.114] 
    ens8:
      dhcp4: false
      addresses: [<mpi_address>/24]
      optional: true
      routes:
        - to: 192.168.100.0/24
          via: 192.168.100.1
      nameservers:
        addresses: [192.168.100.1, 114.114.114.114] 
  version: 2